import { z } from 'zod';

export const ReportSectionSchema = z.object({
  title: z.string(),
  contentMarkdown: z.string(),
  keyMetrics: z.record(z.string()).optional(),
});

export const ReportEvidenceItemSchema = z.object({
  id: z.string(),
  claim: z.string(),
  sourceDomain: z.string(),
  observationTimestamp: z.string(),
  verifiedSynthetic: z.boolean(),
});

export const ExecutiveReportSchema = z.object({
  id: z.string(),
  runId: z.string(),
  title: z.string(),
  generatedAt: z.string(),
  disclaimer: z.string().default('SYNTHETIC DEMO DATA - Generated by Agentic Ops Portfolio Simulation Engine'),
  executiveSummary: z.string(),
  marketOverview: z.string(),
  competitiveChangesSummary: z.string(),
  pricingAnalysisSummary: z.string(),
  opportunitiesSummary: z.string(),
  sections: z.array(ReportSectionSchema),
  evidenceList: z.array(ReportEvidenceItemSchema),
  methodology: z.string(),
  executionMetadata: z.object({
    totalExecutionTimeMs: z.number(),
    orchestratorModel: z.string(),
    subagentsInvoked: z.number(),
    syntheticSourcesCount: z.number(),
    normalizedRecords: z.number(),
  }),
});

export type ExecutiveReport = z.infer<typeof ExecutiveReportSchema>;
