import { AgentDefinition } from '@/types/agents';

export const AGENT_DEFINITIONS: Record<string, AgentDefinition> = {
  supervisor: {
    id: 'supervisor',
    name: 'SUPERVISOR',
    role: 'Orchestrator & Task Planner',
    description: 'Central orchestrator decomposing objectives into subagent tasks, monitoring state transitions, and driving graph convergence.',
    avatarColor: '#7C5CFF',
    badge: 'LangGraph Orchestrator',
    framework: ['LangGraph', 'LangChain', 'OpenAI (Private Adapter)'],
    responsibilities: [
      'Ingest high-level business objective',
      'Decompose problem into structured execution plan',
      'Delegate tasks to specialized subagents',
      'Track state and inspect intermediate payloads',
      'Detect simulated tool failure and trigger fallback recovery',
      'Consolidate state graph and trigger Executive Report generation',
      'Finalize execution lifecycle and generate telemetry',
    ],
    tools: [
      {
        id: 'tool-graph-planner',
        name: 'Graph State Planner',
        description: 'Compiles high-level prompt into LangGraph node sequence.',
        status: 'IDLE',
        category: 'analysis',
        environment: 'SIMULATED',
      },
      {
        id: 'tool-state-consolidator',
        name: 'State Consolidator',
        description: 'Merges subagent outputs into shared state memory.',
        status: 'IDLE',
        category: 'normalization',
        environment: 'SIMULATED',
      },
    ],
  },

  research: {
    id: 'research',
    name: 'RESEARCH AGENT',
    role: 'Market Research Specialist',
    description: 'Specialized agent inspecting competitor endpoints, parsing pricing catalogs, and compiling structured datasets.',
    avatarColor: '#19C3FF',
    badge: 'Data Extraction Node',
    framework: ['LangChain Tools', 'Playwright (Private Adapter)', 'Zod Schemas'],
    responsibilities: [
      'Analyze approved synthetic competitor domains',
      'Collect product specifications and pricing matrix tiers',
      'Extract volume discounts, add-ons, and subscription rates',
      'Normalize attributes across differing schemas',
      'Assemble validated dataset artifact',
      'Transmit dataset to Analysis Agent via structured message',
    ],
    tools: [
      {
        id: 'tool-browser-research',
        name: 'Browser Research (Synthetic Adapter)',
        description: 'Simulated web navigation and catalog retrieval.',
        status: 'IDLE',
        category: 'scraping',
        environment: 'SIMULATED',
      },
      {
        id: 'tool-page-parser',
        name: 'Page Parser (Synthetic Adapter)',
        description: 'Extracts DOM elements, pricing tables, and feature tags.',
        status: 'IDLE',
        category: 'parsing',
        environment: 'SIMULATED',
      },
      {
        id: 'tool-pricing-extractor',
        name: 'Pricing Extractor',
        description: 'Extracts currency, billing cycles, discounts, and deltas.',
        status: 'IDLE',
        category: 'normalization',
        environment: 'SIMULATED',
      },
      {
        id: 'tool-data-normalizer',
        name: 'Data Normalizer',
        description: 'Validates records with Zod and unifies schemas.',
        status: 'IDLE',
        category: 'normalization',
        environment: 'SIMULATED',
      },
    ],
  },

  analysis: {
    id: 'analysis',
    name: 'ANALYSIS AGENT',
    role: 'Business Intelligence Analyst',
    description: 'Quantitative analytics agent computing price variances, discovering market patterns, and prioritizing strategic actions.',
    avatarColor: '#25D695',
    badge: 'BI Analytics Node',
    framework: ['LangChain OutputParser', 'Zod Structured Output'],
    responsibilities: [
      'Ingest normalized competitor dataset',
      'Compare product tiers across competitors',
      'Detect pricing deltas and variance trends',
      'Identify strategic market patterns (e.g. margin shift, bundling)',
      'Calculate key pricing indicators',
      'Classify high-impact opportunities with urgency tiers',
      'Produce validated structured output to Report Agent',
    ],
    tools: [
      {
        id: 'tool-price-variance-engine',
        name: 'Price Variance Engine',
        description: 'Calculates delta percentages and statistical spread.',
        status: 'IDLE',
        category: 'analysis',
        environment: 'SIMULATED',
      },
      {
        id: 'tool-pattern-detector',
        name: 'Market Pattern Detector',
        description: 'Clusters competitor moves into strategic shifts.',
        status: 'IDLE',
        category: 'analysis',
        environment: 'SIMULATED',
      },
      {
        id: 'tool-opportunity-ranker',
        name: 'Opportunity Ranker',
        description: 'Prioritizes counter-actions by revenue impact and urgency.',
        status: 'IDLE',
        category: 'analysis',
        environment: 'SIMULATED',
      },
    ],
  },

  report: {
    id: 'report',
    name: 'REPORT AGENT',
    role: 'Executive Intelligence Reporter',
    description: 'Synthesis specialist converting structured analytical outputs into executive intelligence briefs and audit evidence.',
    avatarColor: '#F5B942',
    badge: 'Executive Synthesis Node',
    framework: ['LangChain PromptTemplate', 'Markdown Formatter', 'Zod'],
    responsibilities: [
      'Receive structured findings, patterns, and opportunities',
      'Compile high-level executive summary',
      'Draft competitive movement section with direct quotes and evidence',
      'Attach synthetic sources and methodology disclosures',
      'Generate final executive_report.md artifact',
      'Notify Supervisor of run completion',
    ],
    tools: [
      {
        id: 'tool-markdown-synthesizer',
        name: 'Markdown Synthesizer',
        description: 'Generates structured C-level executive briefing documents.',
        status: 'IDLE',
        category: 'reporting',
        environment: 'SIMULATED',
      },
      {
        id: 'tool-evidence-compiler',
        name: 'Evidence & Source Compiler',
        description: 'Binds analytical claims to verified synthetic snapshots.',
        status: 'IDLE',
        category: 'reporting',
        environment: 'SIMULATED',
      },
    ],
  },
};
